<?xml version="1.0" ?>
<!DOCTYPE project>
<project default="main">

    <property environment="env"/>

    <path id="classpath">
        <fileset dir="lib" includes="**/*.jar"/>
    </path>
	
	<target name="jdoc" depends="clean, javadoc" description="Main javadoc">
	    <echo>Building and Archiving the Javadocs</echo>
	</target>
	
    <target name="main" depends="clean, compile, compress, javadoc" description="Main target">
        <echo>Building the .jar file.</echo>
    </target>
	
	<target name="clean" description="Cleans project">
		<echo>Cleaning</echo>
		<delete failonerror="false">
			<fileset dir="bin" includes="**/*" />
			<fileset dir="javadoc" includes="**/*" />
		</delete>
		<delete file="VaultReloaded.jar" />
		<mkdir dir="bin"/>
	</target>
  
    <target name="compile" description="Compilation target">
    	<echo>Compiling</echo>
        <javac srcdir="." destdir="bin" debug="on" debuglevel="lines,vars,source" classpathref="classpath" includeantruntime="false" />
    	<copy file="plugin.yml" tofile="bin/plugin.yml" />
    	<replace file="bin/plugin.yml" token="b000" value="b${env.BUILD_NUMBER}" />
    </target>
  
  <target name="compress" description="Compression target">
	<echo>Compressing</echo>
        <jar jarfile="VaultReloaded.jar" basedir="bin" includes="eu/**/*, plugin.yml, props/*">
		<manifest>
			<attribute name="Built-By" value="${user.name}" />
		</manifest>
        </jar>
    	<delete dir="bin" />
  </target>
	
  <target name="javadoc" description="Generate JavaDoc">
  	<delete dir="/var/www/javadoc/vaultreloaded" includes="**/*" failonerror="false" />
	<javadoc packagenames="eu.gabbooo.vaultreloaded.economy,eu.gabbooo.vaultreloaded.permission,eu.gabbooo.vaultreloaded.chat"
			sourcepath="src"
			destdir="/var/www/javadoc/vaultreloaded"
			access="public"
			windowtitle="VaultReloaded"
			verbose="false"
			author="true"
			version="true">
	    <link href="http://docs.oracle.com/javase/7/docs/api/" />
        <link href="http://jd.bukkit.org/apidocs/" />

		<classpath>
			<fileset dir="lib" includes="**/*.jar"/>
		</classpath>
		<bottom>
			<![CDATA[<b>MilkBowl, 2013</b>]]>
		</bottom>
	</javadoc>
  </target>
</project>
